In [4]:
import numpy as np

In [8]:
def python_sum(n):
    """
    Python----Realize the addition of array
    @param n: array lenth
    """
    a = [i**2 for i in range(n)]
    print(a)
    b = [i**3 for i in range(n)]
    print(b)
    c = []
    for i in range(n):
        c.append(a[i]+b[i])
    return c

In [5]:
import numpy as np
a=np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [6]:
b=a.reshape((4,2))
b

ValueError: cannot reshape array of size 4 into shape (4,2)

In [7]:
a.append(14,8,9,)
a




AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)



x    1
y    7
z    2
dtype: int64


In [11]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)



day1    420
day2    380
day3    390
dtype: int64


In [12]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64


In [13]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [15]:
import numpy as np
a= np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [16]:
a*2
a

array([0, 1, 2, 3, 4, 5])

In [17]:
a=a*2
a

array([ 0,  2,  4,  6,  8, 10])

In [18]:
a


array([ 0,  2,  4,  6,  8, 10])

In [20]:
c=a**2
print(c)


[  0   4  16  36  64 100]


In [21]:
a

array([ 0,  2,  4,  6,  8, 10])

In [1]:
k=[0,1,2,3,4,5,6]*2
k


[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]

In [23]:
a=np.array([2,3,4,5,6])
a

array([2, 3, 4, 5, 6])

In [5]:
import numpy as np

In [6]:
y = np.array([[1,2,3],[4,5,6]])

In [7]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
y.shape[0]

2

In [9]:
y.shape[1]

3

In [10]:
y.shape

(2, 3)

In [11]:
m = np.array([[1,2,3],[4,5,6]])

In [12]:
result=np.tile(m,(1,4))

In [13]:
result

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [14]:
result1=np.tile(m,(3,1))
result1

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
result=np.tile(m,(1,4))
result

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [24]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
sum1=np.sum(m,axis=1)

In [34]:
sum1

array([ 6, 15])

In [43]:
import numpy as np
x = np.array([3,1,2])
x=np.argsort(x,axis=0)


In [44]:
x

array([1, 2, 0])