In [9]:
import numpy as np

In [14]:
def python_sum(n):
    """
    Python----Realize the addition of array
    @param n: array lenth
    """
    a = [i**2 for i in range(n)]
    print(a)
    b = [i**3 for i in range(n)]
    print(b)
    c = []
    for i in range(n):
        c.append(a[i]+b[i])
    return c

python_sum(8)


[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 8, 27, 64, 125, 216, 343]


[0, 2, 12, 36, 80, 150, 252, 392]

In [11]:
# a = np.array(1,2,3,4)      # WRONG
a = np.array([2,3,4])
b = np.array([1.2, 3.5, 5.1])
print(a)
print(b)
print('*'*100)

#c = np.array([(1.5, 2, 3), (4, 5, 6)])    # Integer is converted to floating point
c = np.array([
                [1.5, 2, 3], 
                [4, 5, 6]
             ])
print(c)


[2 3 4]
[1.2 3.5 5.1]
****************************************************************************************************
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [15]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2, 10, 2)


array([2, 4, 6, 8])

In [17]:
# Create all 0 array？
a = np.zeros( (3,4) )
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
d = np.eye(5)     # Diagonal array
print(d)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
print(a.dtype)
print('*'*100)
b = a.astype(float)
print(b.dtype)

float64
****************************************************************************************************
float64


In [20]:
# numpy.reshape(arr, newshape, order='C')
# 'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。
a = np.arange(8)
print ('original array：')
print (a)
print ('\n')

c = a.shape
print(c)
 
b = a.reshape(2,4)
print(b.shape)
print ('Modified array：')
print (b)


original array：
[0 1 2 3 4 5 6 7]


(8,)
(2, 4)
Modified array：
[[0 1 2 3]
 [4 5 6 7]]


In [21]:
data = np.loadtxt('***.csv', delimiter=',')


OSError: ***.csv not found.

In [22]:
data1 = np.loadtxt('../data/US_video_data_numbers.csv', delimiter=',', dtype=int)
print(data1)

OSError: ../data/US_video_data_numbers.csv not found.

In [23]:
X = np.arange(20).reshape(4, 5)
print(X)
X[0, 0]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


0

In [ ]:
import sklearn
